services:
  front:
    image: nginx:latest
    container_name: front
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./front-end:/www
      - ./.docker/nginx/front.conf:/etc/nginx/conf.d/default.conf
  back:
    image: nginx:latest
    container_name: back
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./back-end:/www
      - ./.docker/nginx/back.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm
    volumes:
      - ./back-end:/www
